server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/one?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

myurls:
  url: http://localhost:8081
  methods:
    getTitles: /secondCategory/secondCode/
    postTest: /secondCategory/post
    tt: /secondCategory/tt

#spring:
#  profiles:
#    active: @profileActive@
#  redis:
#    host: 127.0.0.1
#    port: 6379
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/one?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

